<?php

return [
    'retail' => [
        'label' => 'Retail / Supermarket',
        'description' => 'General store, supermarket, stationery, gifts & FMCG',
        'icon' => 'bi-cart3',
        'pos_mode' => 'retail',
        'theme_preset' => 'classic-retail',
        'default_units' => ['piece', 'box', 'pack', 'dozen', 'kg', 'liter'],
        'default_categories' => ['Groceries', 'Beverages', 'Snacks', 'Household', 'Personal Care', 'Dairy'],
        'track_expiry_default' => false,
        'default_pricing_mode' => 'fixed',
        'extra_capabilities' => ['delivery', 'website'],
        'tax_rates' => [0, 5, 12, 18, 28],
    ],
    'fresh_perishable' => [
        'label' => 'Fresh / Perishable',
        'description' => 'Flower shop, fish market, poultry, fruits & vegetables',
        'icon' => 'bi-droplet-half',
        'pos_mode' => 'fresh',
        'theme_preset' => 'fresh-market',
        'default_units' => ['kg', 'g', 'piece', 'dozen', 'bunch', 'box'],
        'default_categories' => ['Fresh Items', 'Daily Specials', 'Loose Produce', 'Bulk Sourcing'],
        'track_expiry_default' => true,
        'default_shelf_life_days' => 3,
        'default_pricing_mode' => 'weight',
        'extra_capabilities' => ['suppliers', 'delivery', 'website'],
        'tax_rates' => [0, 5, 12],
    ],
    'restaurant' => [
        'label' => 'Restaurant / Café',
        'description' => 'Dine-in, takeaway, café, bakery & cloud kitchen',
        'icon' => 'bi-cup-hot',
        'pos_mode' => 'restaurant',
        'theme_preset' => 'restaurant-menu',
        'default_units' => ['plate', 'portion', 'piece', 'cup', 'glass', 'box'],
        'default_categories' => ['Starters', 'Main Course', 'Beverages', 'Desserts', 'Quick Bites', 'Combos'],
        'track_expiry_default' => false,
        'default_pricing_mode' => 'fixed',
        'extra_capabilities' => ['restaurant', 'delivery', 'website'],
        'tax_rates' => [0, 5, 18],
    ],
    'service' => [
        'label' => 'Service Business',
        'description' => 'Salon, repair shop, clinic, spa & laundry',
        'icon' => 'bi-scissors',
        'pos_mode' => 'service',
        'theme_preset' => 'service-studio',
        'default_units' => ['service', 'session', 'hour', 'package'],
        'default_categories' => ['Core Services', 'Express Care', 'Packages', 'Add-ons'],
        'track_expiry_default' => false,
        'default_pricing_mode' => 'fixed',
        'extra_capabilities' => ['delivery', 'website'],
        'tax_rates' => [0, 5, 18],
    ],
    'hybrid' => [
        'label' => 'Hybrid / Multi-category',
        'description' => 'Retail + fresh counter + delivery & custom services',
        'icon' => 'bi-shop',
        'pos_mode' => 'hybrid',
        'theme_preset' => 'modern-hybrid',
        'default_units' => ['piece', 'kg', 'box', 'service', 'dozen', 'bunch'],
        'default_categories' => ['Retail Goods', 'Fresh Specials', 'Services', 'Packages'],
        'track_expiry_default' => true,
        'default_shelf_life_days' => 5,
        'default_pricing_mode' => 'fixed',
        'extra_capabilities' => ['suppliers', 'restaurant', 'delivery', 'website'],
        'tax_rates' => [0, 5, 12, 18, 28],
    ],
];

